/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Clases.ComboBoxItem;
import Clases.Curso;
import Clases.Documento;
import Clases.EstadoDocumento;
import Clases.Mensaje;
import Clases.ObjetoPerdido;
import MySQL.Consultas;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

public class GUI_Alumno extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form GUI_Alumno
     */
    
    ArrayList<Mensaje> mensajes;
    ArrayList<ObjetoPerdido> objetos;
    
    public GUI_Alumno() {
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            Consultas.ComboCursos(combo_cursos);
        } catch (SQLException ex) {
            Logger.getLogger(GUI_Alumno.class.getName()).log(Level.SEVERE, null, ex);
        }
        lbl_bienvenida.setText("Bienvenido "+Consultas.alumno_Loggeado.getNombre()+"!");
        
        CARGAR_BANDEJA_DE_ENTRADA();
        CARGAR_OBJETOS_PERDIDOS();
    }
    
    public void CARGAR_OBJETOS_PERDIDOS()
    {
        objetos = new ArrayList<>();
        objetos = Consultas.ObtenerObjetosNOReclamados();
        strip_objetos.removeAll();
        for (ObjetoPerdido objeto:objetos) {
            JMenuItem item = new JMenuItem(objeto.detalles);
            item.addActionListener(this);
            strip_objetos.add(item);
            objeto.item = item;
        }
    }
    
    public void CARGAR_BANDEJA_DE_ENTRADA()
    {
        mensajes = new ArrayList<>();
        ArrayList<EstadoDocumento> estados = Consultas.ObtenerEstadosDelAlumno(Consultas.alumno_Loggeado);
        for (EstadoDocumento estado : estados) {
            
            Curso curso = Consultas.ObtenerCursoDelDocumento(estado.getDocumento_cod_documento());
            Documento documento = Consultas.ObtenerDocumento(estado.getDocumento_cod_documento());
            JMenuItem item = new JMenuItem(curso.getNombre());
            item.setVisible(false);
            item.addActionListener(this);
            
            if(estado.getEstado()==1)
            {
                item.setVisible(true);
            }
            stripBandejaEntrada.add(item);
            Mensaje mensaje = new Mensaje();
            mensaje.setEstado(estado);
            mensaje.setMenuItem(item);
            mensajes.add(mensaje);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_bienvenida = new javax.swing.JLabel();
        lbl_bienvenida1 = new javax.swing.JLabel();
        combo_cursos = new javax.swing.JComboBox<>();
        btn_seleccionar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        stripBandejaEntrada = new javax.swing.JMenu();
        strip_objetos = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_bienvenida.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_bienvenida.setText("Bienvenido Nombre!");

        lbl_bienvenida1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_bienvenida1.setText("Asignar Cursos");

        combo_cursos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btn_seleccionar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_seleccionar.setText("Asignar");
        btn_seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_seleccionarActionPerformed(evt);
            }
        });

        stripBandejaEntrada.setText("Bandeja de Entrada");
        jMenuBar1.add(stripBandejaEntrada);

        strip_objetos.setText("Objetos Perdidos");
        jMenuBar1.add(strip_objetos);

        jMenu3.setText("Cerrar Sesion");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu3MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_bienvenida)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(lbl_bienvenida1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(combo_cursos, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(btn_seleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(lbl_bienvenida)
                .addGap(29, 29, 29)
                .addComponent(lbl_bienvenida1)
                .addGap(18, 18, 18)
                .addComponent(combo_cursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_seleccionar)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MousePressed
        // TODO add your handling code here:
        this.dispose();
        GUI_Login gui = new GUI_Login();
        gui.show();
    }//GEN-LAST:event_jMenu3MousePressed

    private void btn_seleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_seleccionarActionPerformed
        // TODO add your handling code here:
        int cod_curso = ((ComboBoxItem)combo_cursos.getSelectedItem()).valor;
        if(Consultas.AsignarCursoEstudiante(Consultas.alumno_Loggeado,cod_curso))
        {
            JOptionPane.showMessageDialog(null, "Curso asignado con éxito");
            return;
        }
        JOptionPane.showMessageDialog(null, "Error al tratar de asignar curso");
    }//GEN-LAST:event_btn_seleccionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Alumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Alumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Alumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Alumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Alumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_seleccionar;
    private javax.swing.JComboBox<ComboBoxItem> combo_cursos;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbl_bienvenida;
    private javax.swing.JLabel lbl_bienvenida1;
    private javax.swing.JMenu stripBandejaEntrada;
    private javax.swing.JMenu strip_objetos;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if(mensajes != null)
        {
            for (Mensaje mensaje : mensajes) {
            if((e.getSource().equals(mensaje.getMenuItem())))
            {
                JOptionPane.showMessageDialog(null, "Curso: "+
                        Consultas.ObtenerCursoDelDocumento(mensaje.getEstado().getDocumento_cod_documento()).getNombre()+
                        "\nDocumento: "+Consultas.ObtenerDocumento(mensaje.getEstado().getDocumento_cod_documento()).getDocumento());
                
                Consultas.MarcarLeido(mensaje.getEstado());
            }
        }
        }
        
        if(objetos != null)
        {
            for(ObjetoPerdido objeto: objetos)
        {
            if(e.getSource().equals(objeto.item))
            {
                switch (JOptionPane.showConfirmDialog(null, "Objeto: "+objeto.detalles+
                        "\nLugar encontrado: "+objeto.lugar+
                        "\nFecha encontrado: "+objeto.fecha+
                        "\n\nMarcar como tuyo?", "Objeto Perdido", JOptionPane.YES_NO_CANCEL_OPTION)) {
                    case JOptionPane.CANCEL_OPTION:
                        break;
                    case JOptionPane.YES_OPTION:
                        Consultas.MarcarReclamo(objeto);
                        JOptionPane.showMessageDialog(null, "Objeto reclamado con éxito!");
                        CARGAR_OBJETOS_PERDIDOS();
                        break;
                    case JOptionPane.NO_OPTION:
                        break;
                    default:
                        break;
                }
            }
        }
        }
    }
}
